apiVersion: v1
kind: Pod
metadata:
  name: simple-container-task1  
  labels:
    app: my-app 
    bundle: /root/new #bundle path of pause       
spec:
  containers:
    - name: main-container     
      image: /root/new1 # bundle path
      args:                            
        - "sleep"                   
        - "10000"            
      ports:
        - containerPort: 80