apiVersion: v1
kind: Pod
metadata:
  name: simple-container-task  
  labels:
    app: my-app 
    bundle: /root/test        
spec:
  containers:
    - name: main-container     
      image: /root/test1  # bundle path
      args:                            
        - "sleep"                   
        - "10000"            
      ports:
        - containerPort: 80
    - name: main-container2     
      image: /root/test2  # bundle path
      args:                            
        - "sleep"                    
        - "10000"           
      ports:
        - containerPort: 80