apiVersion: v1
kind: Pod
metadata:
  name: simple-container-task  
  labels:
    app: my-app 
    bundle: /root/test        
spec:
  containers:
    - name: main-container     
      image: /root/test1  # 将 image 设置为 bundle 路径
      args:                              # 添加 args 参数
        - "sleep"                    # 示例参数，可以根据需要修改
        - "10000"            # 示例参数，可以根据需要修改
      ports:
        - containerPort: 80
    - name: main-container2     
      image: /root/test2  # 将 image 设置为 bundle 路径
      args:                              # 添加 args 参数
        - "sleep"                    # 示例参数，可以根据需要修改
        - "10000"            # 示例参数，可以根据需要修改
      ports:
        - containerPort: 80